build.gradle

pipeline setup

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.preview.template.yaml
charts/ccpay-notifications-service/values.yaml

Chart update

---

catalog-info.yaml
charts/ccpay-notifications-service/Chart.yaml

See [Slack Announcement](https://hmcts-reform.slack.com/archives/CA4F2MAFR/p1661337390085229)
Ping `@Tim J` on Slack if any questions

Add backstage configuration file

---

build.gradle
charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.preview.template.yaml
config/owasp/suppressions.xml
cve-resolution-strategy.gradle
src/smokeTest/java/uk/gov/hmcts/reform/notifications/smoketests/SmokeTest.java

added CVE fixes and upgraded java version

---

src/main/resources/db/changelog/db.changelog-0.3.yaml
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/db.changelog-master.yaml

PAY-5782 Adding template_preview alter script.

---

config/owasp/suppressions.xml
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/variables.tf

creating demo int db for notif service

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml

PAY-5782 Chart version upgrade

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/notifications/service/NotificationServiceImpl.java

assign refund ref in doc preview

---

src/functionalTest/java/uk/gov/hmcts/reform/notifications/functional/NotificationsServiceFunctionalTest.java

ft added-PAY-5825

---

src/main/java/uk/gov/hmcts/reform/notifications/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/notifications/controllers/NotificationController.java

Pay 5782 with auth

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/notifications/dtos/request/RefundNotificationEmailRequest.java
src/main/java/uk/gov/hmcts/reform/notifications/dtos/request/RefundNotificationLetterRequest.java
src/main/java/uk/gov/hmcts/reform/notifications/service/NotificationServiceImpl.java
src/test/java/uk/gov/hmcts/reform/notifications/controllers/NotificationControllerTest.java

PAY-5873 remove Unable to apply refund to Card

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml
config/owasp/suppressions.xml

Adding xuiwebapp in OIDC Audience list

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml

chart version update and added xui in oidc

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml

Updating OIDC Audience list

---

src/main/java/uk/gov/hmcts/reform/notifications/mapper/NotificationTemplateResponseMapper.java
src/main/resources/db/changelog/db.changelog-0.5.yaml

liquibase changes for service contact

---

build.gradle
charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml
src/main/resources/application.yaml

post look up secert read

---

Jenkinsfile_CNP
Jenkinsfile_nightly
build.gradle

jar update

---

config/owasp/suppressions.xml

suppressing cve, no fix available

---

charts/ccpay-notifications-service/Chart.yaml
cve-resolution-strategy.gradle

upgrading java charts and commons fileupload to v1.5

---

src/main/resources/db/changelog/db.changelog-0.5.yaml

damages add in service contact

---

src/functionalTest/resources/application-functional.yaml

FT pointing to localhost for test.

---

config/owasp/suppressions.xml

suppressed new cve

---

config/owasp/suppressions.xml
cve-resolution-strategy.gradle

Initial PR change

---

charts/ccpay-notifications-service/Chart.yaml

https://tools.hmcts.net/jira/browse/PAY-4884
Updated Chart Java to 4.0.13.
```
[ ] Yes
[x] No
```

PAY-4884: Update Chart Java to latest version

---

src/main/resources/db/changelog/db.changelog-0.6.yaml
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/db/changelog/db.changelog-master.yaml

added insert sql statements in 0.6.yaml

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.preview.template.yaml
config/owasp/suppressions.xml
src/functionalTest/resources/application-functional.yaml

https://tools.hmcts.net/jira/browse/PAY-5997
Updating to support new private dns entry and add suppression for an issue with no known fix.
```
[ ] Yes
[x] No
```

PAY-5997: Updating to support new private dns entry

---

config/owasp/suppressions.xml

Fix cves
```
[ ] Yes
[x] No
```

CVE-2023-28709

---

config/owasp/suppressions.xml

CVE expiry Date amended to 30/10/2023
```
[ ] Yes
[x] No
```

CVE expiry update

---

Jenkinsfile_nightly

PAY_6219
Slack chanel name updated to fee-pay-nightly-pipeline
```
[ ] Yes
[ x] No
```

channel name changed to fee-pay-nightly-pipeline

---

Jenkinsfile_nightly

PAY_6219
Rename slack channel to fee-pay-nightly-pipeline
```
[ ] Yes
[ X ] No
```

fee-pay-nightly-pipeline rename slack chanel

---

src/main/java/uk/gov/hmcts/reform/notifications/config/security/SpringSecurityConfiguration.java

https://tools.hmcts.net/jira/browse/PAY-6395
Update to allow access to swagger pages.
```
[ ] Yes
[x] No
```

PAY-6395: Add access to swagger pages.

---

audit.json
build.gradle

https://tools.hmcts.net/jira/browse/PAY-6510
Pipeline fixes.
```
[ ] Yes
[x] No
```

Pay 6510 pipeline fixes

---

.github/renovate.json

PAY_6547
rennovate fix added
```
[ ] Yes
[ X ] No
```

rennovate fix added

---

.github/renovate.json

PAY-6574: Renovate
[PAY-6574] (https://tools.hmcts.net/jira/browse/PAY-6574).

     PAY-6574: Renovate

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6592
```
[ ] Yes
[X] No
```

PAY-6592-CVE-2023-0833 suppressed.

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml
config/owasp/suppressions.xml

PAY_6611
Version update and CVE fix
```
[ ] Yes
[ x ] No
```

version update

---

infrastructure/main.tf
infrastructure/provider.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PAY-6629
Flexible server created
```
[ ] Yes
[X] No
```

PAY-6629-Flexible Server db created

---

infrastructure/main.tf

PAY-6629
rename flexible server name
```
[ ] Yes
[X] No
```

PAY-6629-Flexible Server db renamed

---

charts/ccpay-notifications-service/Chart.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/PAY-6701
Force access to flexible server db
```
[ ] Yes
[X] No
```

PAY-6701 Force Access to flexible db

---

build.gradle
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/PAY-6715
amend original vault values to pickup flexible db
```
[ ] Yes
[x] No
```

PAY-6713 amend original vault values to pickup flexible DB

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6715
Added some suppression, will be fixed in the next springboot update.
```
[ ] Yes
[x] No
```

PAY-6715: Update to fix/suppress dependencies

---

charts/ccpay-notifications-service/Chart.yaml
charts/ccpay-notifications-service/values.yaml
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PAY-6659
To Decommission v11 dtabase
```
[ ] Yes
[x] No
```

PAY-6659 notification db decommissioned

---

config/owasp/suppressions.xml
cve-resolution-strategy.gradle

https://tools.hmcts.net/jira/browse/PAY-6220
```
[ ] Yes
[ ] No
```

PAY-6220: Fix CVE-2022-1471

---

build.gradle
config/owasp/suppressions.xml
cve-resolution-strategy.gradle

https://tools.hmcts.net/jira/browse/PAY-7124
Address High Vulnerabilities
```
[ ] Yes
[x] No
```

PAY-7124: Address High Vulnerabilities
